export default [
  { "country": "Afghanistan", "continent": "Asia", "code": "AF" },
  { "country": "Albania", "continent": "Europe", "code": "AL" },
  { "country": "Algeria", "continent": "Africa", "code": "DZ" },
  { "country": "Andorra", "continent": "Europe", "code": "AD" },
  { "country": "Angola", "continent": "Africa", "code": "AO" },
  { "country": "Antigua and Barbuda", "continent": "North America", "code": "AG" },
  { "country": "Argentina", "continent": "South America", "code": "AR" },
  { "country": "Armenia", "continent": "Asia", "code": "AM" },
  { "country": "Australia", "continent": "Oceania", "code": "AU" },
  { "country": "Austria", "continent": "Europe", "code": "AT" },
  { "country": "Azerbaijan", "continent": "Asia", "code": "AZ" },
  { "country": "Bahamas", "continent": "North America", "code": "BS" },
  { "country": "Bahrain", "continent": "Asia", "code": "BH" },
  { "country": "Bangladesh", "continent": "Asia", "code": "BD" },
  { "country": "Barbados", "continent": "North America", "code": "BB" },
  { "country": "Belarus", "continent": "Europe", "code": "BY" },
  { "country": "Belgium", "continent": "Europe", "code": "BE" },
  { "country": "Belize", "continent": "North America", "code": "BZ" },
  { "country": "Benin", "continent": "Africa", "code": "BJ" },
  { "country": "Bhutan", "continent": "Asia", "code": "BT" },
  { "country": "Bolivia", "continent": "South America", "code": "BO" },
  { "country": "Bosnia", "continent": "Europe", "code": "BA" },
  { "country": "Botswana", "continent": "Africa", "code": "BW" },
  { "country": "Brazil", "continent": "South America", "code": "BR" },
  { "country": "Brunei", "continent": "Asia", "code": "BN" },
  { "country": "Bulgaria", "continent": "Europe", "code": "BG" },
  { "country": "Burkina Faso", "continent": "Africa", "code": "BF" },
  { "country": "Burma", "continent": "Asia", "code": "MM" },
  { "country": "Burundi", "continent": "Africa", "code": "BI" },
  { "country": "Cambodia", "continent": "Asia", "code": "KH" },
  { "country": "Cameroon", "continent": "Africa", "code": "CM" },
  { "country": "Canada", "continent": "North America", "code": "CA" },
  { "country": "Central African Republic", "continent": "Africa", "code": "CF" },
  { "country": "Chad", "continent": "Africa", "code": "TD" },
  { "country": "Chile", "continent": "South America", "code": "CL" },
  { "country": "China", "continent": "Asia", "code": "CN" },
  { "country": "Colombia", "continent": "South America", "code": "CO" },
  { "country": "Congo", "continent": "Africa", "code": "CG" },
  { "country": "Costa Rica", "continent": "North America", "code": "CR" },
  { "country": "Cote d'Ivoire", "continent": "Africa", "code": "CI" },
  { "country": "Croatia", "continent": "Europe", "code": "HR" },
  { "country": "Cuba", "continent": "North America", "code": "CU" },
  { "country": "Cyprus", "continent": "Europe", "code": "CY" },
  { "country": "Czechia", "continent": "Europe", "code": "CZ" },
  { "country": "Denmark", "continent": "Europe", "code": "DK" },
  { "country": "Djibouti", "continent": "Africa", "code": "DJ" },
  { "country": "Dominica", "continent": "North America", "code": "DM" },
  { "country": "Dominican Republic", "continent": "North America", "code": "DO" },
  { "country": "Ecuador", "continent": "South America", "code": "EC" },
  { "country": "Egypt", "continent": "Africa", "code": "EG" },
  { "country": "El Salvador", "continent": "North America", "code": "SV" },
  { "country": "Equatorial Guinea", "continent": "Africa", "code": "GQ" },
  { "country": "Eritrea", "continent": "Africa", "code": "ER" },
  { "country": "Estonia", "continent": "Europe", "code": "EE" },
  { "country": "Ethiopia", "continent": "Africa", "code": "ET" },
  { "country": "Fiji", "continent": "Oceania", "code": "FJ" },
  { "country": "Finland", "continent": "Europe", "code": "FI" },
  { "country": "France", "continent": "Europe", "code": "FR" },
  { "country": "Gabon", "continent": "Africa", "code": "GA" },
  { "country": "Gambia", "continent": "Africa", "code": "GM" },
  { "country": "Georgia", "continent": "Asia", "code": "GE" },
  { "country": "Germany", "continent": "Europe", "code": "DE" },
  { "country": "Ghana", "continent": "Africa", "code": "GH" },
  { "country": "Greece", "continent": "Europe", "code": "GR" },
  { "country": "Grenada", "continent": "North America", "code": "GD" },
  { "country": "Guatemala", "continent": "North America", "code": "GT" },
  { "country": "Guinea", "continent": "Africa", "code": "GN" },
  { "country": "Guinea-Bissau", "continent": "Africa", "code": "GW" },
  { "country": "Guyana", "continent": "South America", "code": "GY" },
  { "country": "Haiti", "continent": "North America", "code": "HT" },
  { "country": "Honduras", "continent": "North America", "code": "HN" },
  { "country": "Hungary", "continent": "Europe", "code": "HU" },
  { "country": "Iceland", "continent": "Europe", "code": "IS" },
  { "country": "India", "continent": "Asia", "code": "IN" },
  { "country": "Indonesia", "continent": "Asia", "code": "ID" },
  { "country": "Iran", "continent": "Asia", "code": "IR" },
  { "country": "Iraq", "continent": "Asia", "code": "IQ" },
  { "country": "Ireland", "continent": "Europe", "code": "IE" },
  { "country": "Israel", "continent": "Asia", "code": "IL" },
  { "country": "Italy", "continent": "Europe", "code": "IT" },
  { "country": "Jamaica", "continent": "North America", "code": "JM" },
  { "country": "Japan", "continent": "Asia", "code": "JP" },
  { "country": "Jordan", "continent": "Asia", "code": "JO" },
  { "country": "Kazakhstan", "continent": "Asia", "code": "KZ" },
  { "country": "Kenya", "continent": "Africa", "code": "KE" },
  { "country": "Kuwait", "continent": "Asia", "code": "KW" },
  { "country": "Lao People's Democratic Republic", "continent": "Asia", "code": "LA" },
  { "country": "Latvia", "continent": "Europe", "code": "LV" },
  { "country": "Lebanon", "continent": "Asia", "code": "LB" },
  { "country": "Liberia", "continent": "Africa", "code": "LR" },
  { "country": "Libyan Arab Jamahiriya", "continent": "Africa", "code": "LY" },
  { "country": "Liechtenstein", "continent": "Europe", "code": "LI" },
  { "country": "Lithuania", "continent": "Europe", "code": "LT" },
  { "country": "Luxembourg", "continent": "Europe", "code": "LU" },
  { "country": "Macedonia", "continent": "Europe", "code": "MK" },
  { "country": "Madagascar", "continent": "Africa", "code": "MG" },
  { "country": "Malawi", "continent": "Africa", "code": "MW" },
  { "country": "Malaysia", "continent": "Asia", "code": "MY" },
  { "country": "Maldives", "continent": "Asia", "code": "MV" },
  { "country": "Mali", "continent": "Africa", "code": "ML" },
  { "country": "Malta", "continent": "Europe", "code": "MT" },
  { "country": "Mauritania", "continent": "Africa", "code": "MR" },
  { "country": "Mauritius", "continent": "Africa", "code": "MU" },
  { "country": "Mexico", "continent": "North America", "code": "MX" },
  { "country": "Moldova", "continent": "Europe", "code": "MD" },
  { "country": "Monaco", "continent": "Europe", "code": "MC" },
  { "country": "Mongolia", "continent": "Asia", "code": "MN" },
  { "country": "Montenegro", "continent": "Europe", "code": "ME" },
  { "country": "Morocco", "continent": "Africa", "code": "MA" },
  { "country": "Mozambique", "continent": "Africa", "code": "MZ" },
  { "country": "Namibia", "continent": "Africa", "code": "NA" },
  { "country": "Nepal", "continent": "Asia", "code": "NP" },
  { "country": "Netherlands", "continent": "Europe", "code": "NL" },
  { "country": "New Zealand", "continent": "Oceania", "code": "NZ" },
  { "country": "Nicaragua", "continent": "North America", "code": "NI" },
  { "country": "Niger", "continent": "Africa", "code": "NE" },
  { "country": "Nigeria", "continent": "Africa", "code": "NG" },
  { "country": "Norway", "continent": "Europe", "code": "NO" },
  { "country": "Oman", "continent": "Asia", "code": "OM" },
  { "country": "Pakistan", "continent": "Asia", "code": "PK" },
  { "country": "Panama", "continent": "North America", "code": "PA" },
  { "country": "Papua New Guinea", "continent": "Oceania", "code": "PG" },
  { "country": "Paraguay", "continent": "South America", "code": "PY" },
  { "country": "Peru", "continent": "South America", "code": "PE" },
  { "country": "Philippines", "continent": "Asia", "code": "PH" },
  { "country": "Poland", "continent": "Europe", "code": "PL" },
  { "country": "Portugal", "continent": "Europe", "code": "PT" },
  { "country": "Qatar", "continent": "Asia", "code": "QA" },
  { "country": "Romania", "continent": "Europe", "code": "RO" },
  { "country": "Russia", "continent": "Europe", "code": "RU" },
  { "country": "Rwanda", "continent": "Africa", "code": "RW" },
  { "country": "S. Korea", "continent": "Asia", "code": "KR" },
  { "country": "Saint Kitts and Nevis", "continent": "North America", "code": "KN" },
  { "country": "Saint Lucia", "continent": "North America", "code": "LC" },
  { "country": "Saint Vincent and the Grenadines", "continent": "North America", "code": "VC" },
  { "country": "San Marino", "continent": "Europe", "code": "SM" },
  { "country": "Sao Tome and Principe", "continent": "Africa", "code": "ST" },
  { "country": "Saudi Arabia", "continent": "Asia", "code": "SA" },
  { "country": "Senegal", "continent": "Africa", "code": "SN" },
  { "country": "Serbia", "continent": "Europe", "code": "RS" },
  { "country": "Seychelles", "continent": "Africa", "code": "SC" },
  { "country": "Sierra Leone", "continent": "Africa", "code": "SL" },
  { "country": "Singapore", "continent": "Asia", "code": "SG" },
  { "country": "Slovakia", "continent": "Europe", "code": "SK" },
  { "country": "Slovenia", "continent": "Europe", "code": "SI" },
  { "country": "Somalia", "continent": "Africa", "code": "SO" },
  { "country": "South Africa", "continent": "Africa", "code": "ZA" },
  { "country": "South Sudan", "continent": "Africa", "code": "SS" },
  { "country": "Spain", "continent": "Europe", "code": "ES" },
  { "country": "Sri Lanka", "continent": "Asia", "code": "LK" },
  { "country": "Sudan", "continent": "Africa", "code": "SD" },
  { "country": "Suriname", "continent": "South America", "code": "SR" },
  { "country": "Swaziland", "continent": "Africa", "code": "SZ" },
  { "country": "Sweden", "continent": "Europe", "code": "SE" },
  { "country": "Switzerland", "continent": "Europe", "code": "CH" },
  { "country": "Syrian Arab Republic", "continent": "Asia", "code": "SY" },
  { "country": "Taiwan", "continent": "Asia", "code": "TW" },
  { "country": "Tanzania", "continent": "Africa", "code": "TZ" },
  { "country": "Thailand", "continent": "Asia", "code": "TH" },
  { "country": "Timor-Leste", "continent": "Asia", "code": "TL" },
  { "country": "Togo", "continent": "Africa", "code": "TG" },
  { "country": "Trinidad and Tobago", "continent": "North America", "code": "TT" },
  { "country": "Tunisia", "continent": "Africa", "code": "TN" },
  { "country": "Turkey", "continent": "Asia", "code": "TR" },
  { "country": "UAE", "continent": "Asia", "code": "AE" },
  { "country": "Uganda", "continent": "Africa", "code": "UG" },
  { "country": "UK", "continent": "Europe", "code": "GB" },
  { "country": "Ukraine", "continent": "Europe", "code": "UA" },
  { "country": "Uruguay", "continent": "South America", "code": "UY" },
  { "country": "USA", "continent": "North America", "code": "US" },
  { "country": "Uzbekistan", "continent": "Asia", "code": "UZ" },
  { "country": "Venezuela", "continent": "South America", "code": "VE" },
  { "country": "Vietnam", "continent": "Asia", "code": "VN" },
  { "country": "Western Sahara", "continent": "Africa", "code": "EH" },
  { "country": "Zambia", "continent": "Africa", "code": "ZM" },
  { "country": "Zimbabwe", "continent": "Africa", "code": "ZW" },
]