export default [
  { "country": "Afghanistan", "continent": "Asia" },
  { "country": "Albania", "continent": "Europe" },
  { "country": "Algeria", "continent": "Africa" },
  { "country": "Andorra", "continent": "Europe" },
  { "country": "Angola", "continent": "Africa" },
  { "country": "Antigua and Barbuda", "continent": "North America" },
  { "country": "Argentina", "continent": "South America" },
  { "country": "Armenia", "continent": "Asia" },
  { "country": "Australia", "continent": "Oceania" },
  { "country": "Austria", "continent": "Europe" },
  { "country": "Azerbaijan", "continent": "Asia" },
  { "country": "Bahamas", "continent": "North America" },
  { "country": "Bahrain", "continent": "Asia" },
  { "country": "Bangladesh", "continent": "Asia" },
  { "country": "Barbados", "continent": "North America" },
  { "country": "Belarus", "continent": "Europe" },
  { "country": "Belgium", "continent": "Europe" },
  { "country": "Belize", "continent": "North America" },
  { "country": "Benin", "continent": "Africa" },
  { "country": "Bhutan", "continent": "Asia" },
  { "country": "Bolivia", "continent": "South America" },
  { "country": "Bosnia", "continent": "Europe" },
  { "country": "Botswana", "continent": "Africa" },
  { "country": "Brazil", "continent": "South America" },
  { "country": "Brunei", "continent": "Asia" },
  { "country": "Bulgaria", "continent": "Europe" },
  { "country": "Burkina Faso", "continent": "Africa" },
  { "country": "Burma", "continent": "Asia" },
  { "country": "Burundi", "continent": "Africa" },
  { "country": "Cambodia", "continent": "Asia" },
  { "country": "Cameroon", "continent": "Africa" },
  { "country": "Canada", "continent": "North America" },
  { "country": "Central African Republic", "continent": "Africa" },
  { "country": "Chad", "continent": "Africa" },
  { "country": "Chile", "continent": "South America" },
  { "country": "China", "continent": "Asia" },
  { "country": "Colombia", "continent": "South America" },
  { "country": "Congo", "continent": "Africa" },
  { "country": "Costa Rica", "continent": "North America" },
  { "country": "Cote d'Ivoire", "continent": "Africa" },
  { "country": "Croatia", "continent": "Europe" },
  { "country": "Cuba", "continent": "North America" },
  { "country": "Cyprus", "continent": "Europe" },
  { "country": "Czechia", "continent": "Europe" },
  { "country": "Denmark", "continent": "Europe" },
  { "country": "Djibouti", "continent": "Africa" },
  { "country": "Dominica", "continent": "North America" },
  { "country": "Dominican Republic", "continent": "North America" },
  { "country": "Ecuador", "continent": "South America" },
  { "country": "Egypt", "continent": "Africa" },
  { "country": "El Salvador", "continent": "North America" },
  { "country": "Equatorial Guinea", "continent": "Africa" },
  { "country": "Eritrea", "continent": "Africa" },
  { "country": "Estonia", "continent": "Europe" },
  { "country": "Ethiopia", "continent": "Africa" },
  { "country": "Fiji", "continent": "Oceania" },
  { "country": "Finland", "continent": "Europe" },
  { "country": "France", "continent": "Europe" },
  { "country": "Gabon", "continent": "Africa" },
  { "country": "Gambia", "continent": "Africa" },
  { "country": "Georgia", "continent": "Asia" },
  { "country": "Germany", "continent": "Europe" },
  { "country": "Ghana", "continent": "Africa" },
  { "country": "Greece", "continent": "Europe" },
  { "country": "Grenada", "continent": "North America" },
  { "country": "Guatemala", "continent": "North America" },
  { "country": "Guinea-Bissau", "continent": "Africa" },
  { "country": "Guinea", "continent": "Africa" },
  { "country": "Guyana", "continent": "South America" },
  { "country": "Haiti", "continent": "North America" },
  { "country": "Honduras", "continent": "North America" },
  { "country": "Hungary", "continent": "Europe" },
  { "country": "Iceland", "continent": "Europe" },
  { "country": "India", "continent": "Asia" },
  { "country": "Indonesia", "continent": "Asia" },
  { "country": "Iran", "continent": "Asia" },
  { "country": "Iraq", "continent": "Asia" },
  { "country": "Ireland", "continent": "Europe" },
  { "country": "Israel", "continent": "Asia" },
  { "country": "Italy", "continent": "Europe" },
  { "country": "Jamaica", "continent": "North America" },
  { "country": "Japan", "continent": "Asia" },
  { "country": "Jordan", "continent": "Asia" },
  { "country": "Kazakhstan", "continent": "Asia" },
  { "country": "Kenya", "continent": "Africa" },
  { "country": "Kuwait", "continent": "Asia" },
  { "country": "Lao People's Democratic Republic", "continent": "Asia" },
  { "country": "Latvia", "continent": "Europe" },
  { "country": "Lebanon", "continent": "Asia" },
  { "country": "Liberia", "continent": "Africa" },
  { "country": "Libyan Arab Jamahiriya", "continent": "Africa" },
  { "country": "Liechtenstein", "continent": "Europe" },
  { "country": "Lithuania", "continent": "Europe" },
  { "country": "Luxembourg", "continent": "Europe" },
  { "country": "Macedonia", "continent": "Europe" },
  { "country": "Madagascar", "continent": "Africa" },
  { "country": "Malawi", "continent": "Africa" },
  { "country": "Malaysia", "continent": "Asia" },
  { "country": "Maldives", "continent": "Asia" },
  { "country": "Mali", "continent": "Africa" },
  { "country": "Malta", "continent": "Europe" },
  { "country": "Mauritania", "continent": "Africa" },
  { "country": "Mauritius", "continent": "Africa" },
  { "country": "Mexico", "continent": "North America" },
  { "country": "Moldova", "continent": "Europe" },
  { "country": "Monaco", "continent": "Europe" },
  { "country": "Mongolia", "continent": "Asia" },
  { "country": "Montenegro", "continent": "Europe" },
  { "country": "Morocco", "continent": "Africa" },
  { "country": "Mozambique", "continent": "Africa" },
  { "country": "Namibia", "continent": "Africa" },
  { "country": "Nepal", "continent": "Asia" },
  { "country": "Netherlands", "continent": "Europe" },
  { "country": "New Zealand", "continent": "Oceania" },
  { "country": "Nicaragua", "continent": "North America" },
  { "country": "Niger", "continent": "Africa" },
  { "country": "Nigeria", "continent": "Africa" },
  { "country": "Norway", "continent": "Europe" },
  { "country": "Oman", "continent": "Asia" },
  { "country": "Pakistan", "continent": "Asia" },
  { "country": "Panama", "continent": "North America" },
  { "country": "Papua New Guinea", "continent": "Oceania" },
  { "country": "Paraguay", "continent": "South America" },
  { "country": "Peru", "continent": "South America" },
  { "country": "Philippines", "continent": "Asia" },
  { "country": "Poland", "continent": "Europe" },
  { "country": "Portugal", "continent": "Europe" },
  { "country": "Qatar", "continent": "Asia" },
  { "country": "Romania", "continent": "Europe" },
  { "country": "Russia", "continent": "Europe" },
  { "country": "Rwanda", "continent": "Africa" },
  { "country": "S. Korea", "continent": "Asia" },
  { "country": "Saint Kitts and Nevis", "continent": "North America" },
  { "country": "Saint Lucia", "continent": "North America" },
  { "country": "Saint Vincent and the Grenadines", "continent": "North America" },
  { "country": "San Marino", "continent": "Europe" },
  { "country": "Sao Tome and Principe", "continent": "Africa" },
  { "country": "Saudi Arabia", "continent": "Asia" },
  { "country": "Senegal", "continent": "Africa" },
  { "country": "Serbia", "continent": "Europe" },
  { "country": "Seychelles", "continent": "Africa" },
  { "country": "Sierra Leone", "continent": "Africa" },
  { "country": "Singapore", "continent": "Asia" },
  { "country": "Slovakia", "continent": "Europe" },
  { "country": "Slovenia", "continent": "Europe" },
  { "country": "Somalia", "continent": "Africa" },
  { "country": "South Africa", "continent": "Africa" },
  { "country": "South Sudan", "continent": "Africa" },
  { "country": "Spain", "continent": "Europe" },
  { "country": "Sri Lanka", "continent": "Asia" },
  { "country": "Sudan", "continent": "Africa" },
  { "country": "Suriname", "continent": "South America" },
  { "country": "Swaziland", "continent": "Africa" },
  { "country": "Sweden", "continent": "Europe" },
  { "country": "Switzerland", "continent": "Europe" },
  { "country": "Syrian Arab Republic", "continent": "Asia" },
  { "country": "Taiwan", "continent": "Asia" },
  { "country": "Tanzania", "continent": "Africa" },
  { "country": "Thailand", "continent": "Asia" },
  { "country": "Timor-Leste", "continent": "Asia" },
  { "country": "Togo", "continent": "Africa" },
  { "country": "Trinidad and Tobago", "continent": "North America" },
  { "country": "Tunisia", "continent": "Africa" },
  { "country": "Turkey", "continent": "Asia" },
  { "country": "Turkey", "continent": "Europe" },
  { "country": "UAE", "continent": "Asia" },
  { "country": "Uganda", "continent": "Africa" },
  { "country": "UK", "continent": "Europe" },
  { "country": "Ukraine", "continent": "Europe" },
  { "country": "Uruguay", "continent": "South America" },
  { "country": "USA", "continent": "North America" },
  { "country": "Uzbekistan", "continent": "Asia" },
  { "country": "Venezuela", "continent": "South America" },
  { "country": "Vietnam", "continent": "Asia" },
  { "country": "Western Sahara", "continent": "Africa" },
  { "country": "Zambia", "continent": "Africa" },
  { "country": "Zimbabwe", "continent": "Africa" },
]